{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file3.Test_Credence_003 object at 0x0000015372F60BD0>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file3.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "d8146f9b-fbe1-46a2-a4c6-d949dd40f777-attachment.txt", "type": "text/plain"}], "start": 1691134343649, "stop": 1691134343649, "uuid": "3ddbcbed-3a69-4069-948a-cc406c7af181", "historyId": "b5a535ee3b4f399417f06f2bf4d09172", "testCaseId": "b5a535ee3b4f399417f06f2bf4d09172", "fullName": "test_file3.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_file3"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "DESKTOP-TV0ODVG"}, {"name": "thread", "value": "7384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file3"}]}