{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file3.Test_Credence_003 object at 0x0000022FD1D3E050>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file3.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "ce2fa179-7fd6-4524-882b-88a22a7dc4d7-attachment.txt", "type": "text/plain"}], "start": 1691063855335, "stop": 1691063855335, "uuid": "16fb806b-59d1-422e-82a0-4903244135c3", "historyId": "b5a535ee3b4f399417f06f2bf4d09172", "testCaseId": "b5a535ee3b4f399417f06f2bf4d09172", "fullName": "test_file3.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_file3"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "DESKTOP-TV0ODVG"}, {"name": "thread", "value": "10412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file3"}]}