{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file3.Test_Credence_003 object at 0x000002F023E9C8D0>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file3.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "710440ce-1e4b-43cc-b8d4-35cfa6d8b270-attachment.txt", "type": "text/plain"}], "start": 1691061776280, "stop": 1691061776280, "uuid": "73546740-752e-4467-b4c8-261881888844", "historyId": "b5a535ee3b4f399417f06f2bf4d09172", "testCaseId": "b5a535ee3b4f399417f06f2bf4d09172", "fullName": "test_file3.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_file3"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "DESKTOP-TV0ODVG"}, {"name": "thread", "value": "8272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file3"}]}